repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
        exclude: \.(nb|wl)$
    -   id: trailing-whitespace
        exclude: \.(nb|wl)$
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.29.0'
    hooks:
    -   id: yapf
